<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Firefox WebAutomationTesting"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="40.483">
  <properties />
            <testcase name="loginTest" time="40.483" classname="com.selenium.test.testng.tests.LoginTest">
                <failure type="com.codeborne.selenide.ex.ElementShould"
                  message="Element should have text &apos;帳號或密碼錯誤，請重試一次&apos; {div.validation-summary-errors&gt;ul&gt;li}
Element: &apos;&lt;li value=&quot;0&quot; displayed:false&gt;&lt;/li&gt;&apos;"
              >
<![CDATA[Element should have text '帳號或密碼錯誤，請重試一次' {div.validation-summary-errors>ul>li}
Element: '<li value="0" displayed:false></li>'
Screenshot: file:/Users/ehsn/Selenide-TestNG-ReportNG-Framework/build/reports/tests/1528878718955.1.png
Page source: file:/Users/ehsn/Selenide-TestNG-ReportNG-Framework/build/reports/tests/1528878718955.1.html
Timeout: 4 s.
  com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:66)
  com.codeborne.selenide.commands.Should.should(Should.java:35)
  com.codeborne.selenide.commands.Should.execute(Should.java:29)
  com.codeborne.selenide.commands.Should.execute(Should.java:12)
  com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
  com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:90)
  com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
  com.sun.proxy.$Proxy6.shouldHave(Unknown Source)
  com.selenium.PageObject.LoginPage.loginFail(LoginPage.java:70)
  com.selenium.test.testng.tests.LoginTest.loginTest(LoginTest.java:18)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
